title: Zukane CTF
email: zukane.ctf@gmail.com
description: >- 
  CTF Writeups, mostly focused on crypto
baseurl: "" 
url: "https://zukane.github.io" 
github_username: Zukane
author: Zukane
permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
future: true
